import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers";
import { Github, Linkedin, Mail } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Crypto Next App",
  description: "Generated by @elmi-elmi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex h-screen flex-col items-center justify-center antialiased`}
      >
        <Providers>{children}</Providers>

        <footer className="flex flex-wrap items-center justify-center gap-6">
          <a
            href="https://www.linkedin.com/in/elmialireza/"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            aria-label="LinkedIn"
          >
            <Linkedin className="h-4 w-4" aria-hidden />
            elmialireza
          </a>

          <a
            href="https://github.com/elmi-elmi/crypto-table-task"
            target="_blank"
            rel="noopener noreferrer"
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            aria-label="GitHub"
          >
            <Github className="h-4 w-4" aria-hidden />
            elmi-elmi
          </a>

          <a
            href="mailto:shahrokhelmi@gmail.com"
            className="flex items-center gap-2 hover:underline hover:underline-offset-4"
            aria-label="Email"
          >
            <Mail className="h-4 w-4" aria-hidden />
            Email
          </a>
        </footer>
      </body>
    </html>
  );
}
